config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "boards#index"

  resources :boards do
    resources :lists
  end

  resources :lists do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy

  def self.all_boards(user_id)
    Board.find_by_sql(
      "SELECT *
      FROM boards AS b
      WHERE b.user_id = #{user_id}"
    )
  end

  def self.create_board(p, id)
    Board.find_by_sql(["
      INSERT INTO boards (name, user_id)
      VALUES (:name, :user_id);
    ", {
      name: p[:name],
      user_id: id
    }])
  end
  
  def self.update_board(board_id, p)
    Board.find_by_sql(["
      UPDATE boards AS c
      SET first_name = ?, last_name = ?, email = ?, phone = ?, updated_at = ?
      WHERE c.id = ?
    ;", p[:first_name], p[:last_name], p[:email], p[:phone], DateTime.now, board_id])
  end
  
  def self.delete_board(board_id)
    Board.find_by_sql(["
      DELETE FROM boards AS c
      WHERE c.id = ?
    ;", board_id])
  end





end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = current_user.boards
  end

  def show
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.new(board_params)

   if @board.save
     redirect_to boards_path
   else
     render :new
   end
  end

  def edit
  end

  def update
    if  @board.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    @board.destroy 
    redirect_to boards_path
  end
  
  private
  def board_params
    params.require(:board).permit(:name)
  end
  
  def set_board
      @board = current_user.boards.find(params[:id])
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:edit, :update, :destroy]
  before_action :set_board, except: [:destroy]

  def new
    @list = @board.lists.new
  end

  def create
    @list = @board.lists.new(list_params)

    if @list.save
      redirect_to @board
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to @board
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to board_path(@list.board_id)
  end

  private
    def list_params
      params.require(:list).permit(:name)
    end

    def set_board
      @board = Board.find(params[:board_id])
    end

    def set_list
      @list = List.find(params[:id])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]
  before_action :set_list

  def new
    @task = @list.tasks.new
  end

  def create
    @task = @list.tasks.new(task_params)

    if @task.save
      redirect_to board_path(@list.board_id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to board_path(@list.board_id)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to board_path(@list.board_id)
  end

  private
    def task_params
      params.require(:task).permit(:name, :desc)
    end

    def set_list
      @list = List.find(params[:list_id])
    end

    def set_task
      @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
  <div class = "field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input" %>
  </div>
  <%= f.submit nil, class: "ui green button" %>
<% end %>

app/views/boards/edit.html.erb
<%= render "form" %>

app/views/boards/index.html.erb
<h1>Welcome <%= current_user.first_name%></h1>
<h2>All Boards</h2>
<hr />
<br />

<div class="ui grid">


  <% @boards.each do |board| %>

    <div class="five wide column">

      <div class="ui card">

        <div class="content">
          <div class="header"> <h2><%= link_to board.name, board %></h2> </div>
        </div>
        <div class="content">
          <h4 class="ui sub header">Activity</h4>
          <div class="ui small feed">
            <div class="event">
              <div class="content">
                <div class="summary">
                  <a>Elliot Fu</a> added <a>Jenny Hess</a> to the project
                </div>
              </div>
            </div>
            <div class="event">
              <div class="content">
                <div class="summary">
                  <a>Stevie Feliciano</a> was added as an <a>Administrator</a>
                </div>
              </div>
            </div>
            <div class="event">
              <div class="content">
                <div class="summary">
                  <a>Helen Troy</a> added two pictures
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="extra content">
          <%= link_to 'Edit Board', edit_board_path(board), class: "inverted ui blue button" %>
          <%= link_to 'Delete Board', board, method: :delete, class: "inverted ui red button" %>
        </div>

      </div>


    </div>
    <br />
  <%end%>
    


  <div class="five wide column">
    <h3><%= link_to "+",new_board_path(@board), class: "massive ui green button"%></h3>
  </div> 
</div>

app/views/boards/new.html.erb
<%= render "form" %>

app/views/boards/show.html.erb
<h1><%= @board.name  %> Board</h1>
<br />
<%= link_to 'Back', boards_path, class: "ui blue button" %>
</h1>
<hr />
<br />





<div class="ui grid">


  <% @board.lists.each do |list| %>
    <div class="four wide column">
      <div class="ui card">
        <div class="content">
          <div class="header"> <h2><%=list.name%></h2> </div>
        </div>
        
        <h3><%= link_to '+ Add Task', new_list_task_path(list), class: "ui green bottom attached button" %></h3>
        
        <% list.tasks.each do |task| %>
          <div class="ui card">

            <div class="content">
              <div class="header"> <h3><%=task.name%></h3> </div>
              <br />
              <div class="header"> <h4><%=task.desc%></h4> </div>
            </div>
          
            <div class="ui two bottom attached buttons">
              <%= link_to 'Edit Task', edit_list_task_path(task.list_id, task.id), class: "ui button" %>
              <%= link_to 'Delete Task', list_task_path(task.list_id, task.id), method: :delete, class: "ui button" %>
            </div>
          </div>
          <br />
        <%end%>


        <div class="ui two bottom attached buttons">
          <%= link_to 'Edit List', edit_board_list_path(list.board_id, list.id), class: "inverted ui blue button" %>
          <%= link_to 'Delete List', list, method: :delete, class: "inverted ui red button" %>
        </div>
      </div>
    </div>
    <br />
  <%end%>
    


  <div class="four wide column">
    <h3><%= link_to '+', new_board_list_path(@board), class: "massive ui green button" %></h3>
  </div> 
</div>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">

  <div class="menu">
  </div>

  <div class="right menu">

    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
    <% end %>

    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
    <% else %>
      <%= link_to "Register", new_user_registration_path, class: "item" %>
      <%= link_to "Login", new_user_session_path, class: "item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<h1><%= @list.id ? 'Edit List' : 'Create List' %></h1>
<hr />
<br />



<%= form_for [@board, @list], :html => { class: "ui form" } do |f| %>
  <div class = "field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input" %>
  </div>
  <%= f.submit nil, class: "ui inverted green button" %>
<% end %>

app/views/lists/edit.html.erb
<%=render "form"  %>

app/views/lists/new.html.erb
<%=render "form"  %>

app/views/tasks/_form.html.erb
<h1><%= @task.id ? 'Edit Task' : 'Create Task' %></h1>
<hr />
<br />



<%= form_for [@list, @task], :html => { class: "ui form" } do |f| %>
  <div class = "field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input" %>

    <%= f.label :description %>
    <%= f.text_area :desc, class: "input" %>
  </div>
  <%= f.submit nil, class: "ui inverted green button" %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>

app/views/tasks/new.html.erb
<%= render "form" %>